upstream django {
    server erp_web:8000;
}

server {
    listen 80;
    
     location /static/ {
        alias /var/www/static/;
    }

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
    }
}