# Generated by Django 5.2.12 on 2026-03-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
