# Generated by Django 5.2.12 on 2026-03-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_soft_deleted_alter_vehicle_soft_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='soft_deleted',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='soft_deleted',
            new_name='is_active',
        ),
    ]
