# Generated by Django 5.2.12 on 2026-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_is_active_alter_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
    ]
