# Generated by Django 5.2.12 on 2026-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
